services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  celery-worker:
    volumes:
      - ./backend:/app

  celery-beat:
    volumes:
      - ./backend:/app

  frontend:
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
